version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5328:5328"
    environment:
      - FLASK_ENV=development
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./backend:/app
      - ../src:/app/src
      - ../tools:/app/tools
    working_dir: /app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5328
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - backend
